---
server:
  host: 0.0.0.0
  port: 9091
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  # tls:
  #   key: "/certs/key.pem"
  #   certificate: "/certs/cert.pem"

theme: light

server:
  read_buffer_size: 10485760
  write_buffer_size: 10485760
  path: ""
log:
  level: debug

jwt_secret: 5S54S8YvDn*sNEUuH#3h8Mfch&UP
default_redirection_url: https://auth.localhost

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# duo_api:
#   hostname: hostname
#   integration_key: integration_key
#   secret_key: secret_key

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny

  networks:
    - name: internal
      networks:
        - 10.10.1.0/24
        - 10.145.0.0/16
        - 172.17.0.0/16
        - 172.19.0.0/16
        - 172.22.0.0/16
        - 172.24.0.0/16
        - 172.26.0.0/16
        - 172.29.0.0/16
        - 172.31.0.0/16
        - 10.145.10.0/24

    - name: VPN
      networks: 10.13.0.0/16

  rules:
    - domain: 
        - auth.localhost
        - cdn.localhost
        - plex.localhost
      policy: bypass
    
    - domain:
        - synology.localhost
      policy: bypass
      networks:
        - VPN
        - internal

    - domain:
        - "*.localhost"
      policy: bypass
      networks:
        - VPN
        - internal

    - domain:
        - "*.localhost"
      policy: two_factor
      subject:
        - "group:admins"
        - "group:authelia_admins"
    
    - domain:
        - "*.localhost"
      policy: two_factor
      subject:
        - "group:authelia_powerusers"
 
session:
  name: authelia_session
  domain: localhost
  same_site: lax
  secret: insecure_session_secret
  expiration: 1h
  inactivity: 30m
  remember_me_duration: 6h

  redis:
    host: redis
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  postgres:
    host: postgres
    port: 5432
    database: authelia
    username: root
    password: admin123
    sslmode: disable
  encryption_key: BLeYwz926KtrcLOY7cq0oJDyETivQ8

notifier:
  disable_startup_check: false
  # smtp:
  #   username: no-reply@localhost
  #   password: 8ZLi9Fgo5odWS-nYgrVPcw
  #   host: 10.145.10.254
  #   port: 1025
  #   disable_require_tls: false
  #   disable_html_emails: false
